Login form & style sheet
scrum-gang/jobhub-chrome pull request #9
Opened 2019-02-03 01:37 UTC by CamiloGarciaLaRotta

While this PR focuses primarily on the Login form, integrating the login form to the Chrome extension also implied having a basic working job posting component (Issue #3) and ensuring the style across all components was uniform (Issue #7).

 **Changes:**
- Add a global style linter and formatter (`.editorconfig`)
- Pass to the `Login` and `JobApp` components a handler in the form of a callback to `App`'s reducer.
  this way we achieve conditional rendering of the components without requiring a router.
- Note that the forms are all tab accessible.
- Define the CSS directly into `popup.html`.  I considered it short enough to be added directly inline.
- Make the forms tab-accessible.

**Next Steps:**
- The job application form is not complete. I run into a bug where ReasonReact doesn't allow me to specify the type of input fields: `<input type_="password">`.
- The handlers are currently dummy functions that go back and forth between Login/Logout.

Closes #2 
Closes #7

2019-02-04 00:40 UTC, alexboii requested changes
all looks good, great job, just a few minor changes from comments above

2019-02-04 00:40 UTC, alexboii commented on popup.html
>    <style type="text/css">
can you make this into a separate file?

2019-02-04 00:40 UTC, alexboii commented on src/App.re
>  type route =
why did you change the names to "LoginPage" and "JobAppPage"

I removed them before because it seemed too repetitive to have "Page" at the end of every component

2019-02-04 00:40 UTC, alexboii commented on src/App.re
> +                          submitHandler=(_event => self.send(Logout))
these handlers are going to be removed later though since the reducing is going to be done based on the validity of the login token

2019-02-04 00:40 UTC, alexboii commented on src/JobApp.re
> +        /* TODO: can't add type_="". not sure why not. */
it's `_type`, not `type_`

2019-02-04 00:40 UTC, alexboii commented on src/JobApp.re
> +        /* TODO: can't add type_="". not sure why not. */
it's good that you spotted this though, our version of reason is outdated (0.3.8), will update on master

2019-02-04 00:40 UTC, alexboii commented on src/JobApp.re
> +        /* TODO: can't add type_="". not sure why not. */
tried to update, can't -- some of the dev dependencies rely on an older version of bucklescript which is incompatible with the latest version of reasonreact

2019-02-04 00:43 UTC, alexboii commented
after this is merged I'll start working on a monad for scraping info

2019-02-04 13:38 UTC, CamiloGarciaLaRotta commented on src/App.re
> +                          submitHandler=(_event => self.send(Logout))
agree, although they can be kept for the moment to be able to jump back and forth betweeen the 2 pages right?

2019-02-04 13:40 UTC, CamiloGarciaLaRotta commented on src/JobApp.re
> +        /* TODO: can't add type_="". not sure why not. */
that's very inconvenient. I'll look into that issue too then.

2019-02-04 14:03 UTC, alexboii commented on src/App.re
> +                          submitHandler=(_event => self.send(Logout))
yep

2019-02-04 14:03 UTC, alexboii commented on src/JobApp.re
> +        /* TODO: can't add type_="". not sure why not. */
what's inconvenient? just use `_type`

2019-02-04 14:50 UTC, CamiloGarciaLaRotta commented on src/JobApp.re
> +        /* TODO: can't add type_="". not sure why not. */
oh I thought you meant it wasn't feasible with our version of reasonreact

2019-02-05 00:46 UTC, alexboii approved these changes

2019-02-05 02:03 UTC, merged